import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Projects from "../components/Projects/Project";
import Team from "../components/Team/Team";



export default function Home() {
  return (

    <div className={styles.container}>

      <Projects/>
        <Team/>
      <Head>
        <title>GAIA | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}
